### ISSUE TITLE
Elaborate

### ISSUE THREAD

**Issue by tylerjusfly** [DammyShittu/WeSingAfrica-Capstone#2]
So what are you trying to achieve in this project? 

How do we come in??

**Comment by DammyShittu** [comment]
Hello @tylerjusfly,

I hope this meets you well.

I currently do not understand what you were trying to say in your message.

Kindly expatiate.

Thanks, 😁

**Comment by tylerjusfly** [comment]
Ok. i was just a little bit free this weekend and i felt like contributing to projects, but i'm trying to understand what your project does.
